// Generated by LiveScript 1.3.1
(function(){
  var throttle_call;
  throttle_call = function(f, max_simultaneous){
    var count, waiting, throttled_func;
    if (max_simultaneous == null) {
      max_simultaneous = 1;
    }
    count = 0;
    waiting = [];
    throttled_func = function(params, cb){
      if (count < max_simultaneous) {
        count = count + 1;
        return f(params, function(){
          count = count - 1;
          if (waiting.length > 0) {
            throttled_func.apply(null, waiting.shift());
          }
          return cb.apply(this, arguments);
        });
      } else {
        return waiting.push(arguments);
      }
    };
    return throttled_func;
  };
  module.exports = throttle_call;
}).call(this);
